spring.application.name=cp-analyzer

spring.datasource.url=jdbc:mysql://localhost:3306/cp_analyzer
spring.datasource.username=root
spring.datasource.password=Priya@12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=mysupersecretkeymysupersecretkey
jwt.expiration=86400000